language: python
python:
  - 2.7

###
### Add services
###
services:
  - docker


###
### Global variables
###
env:
  global:
    - MY_DOCKER_NAME="apache-2.2"


###
### Install
###
install:
  - docker version

  # Build docker and pull others
  - docker build -t cytopia/${MY_DOCKER_NAME} .
  - docker pull cytopia/php-fpm-5.6
  - docker pull cytopia/mysql-5.5

  # Create directory with html and php files
  - mkdir -p ~/www
  - mkdir -p ~/tmp/host-mysql-sock
  - echo "Static Html" > ~/www/index.html
  - echo "<?php echo 'Helo world'; ?>" > ~/www/index.php
  - echo "<?php if (mysqli_connect('localhost', 'root', '')) { echo 'YES'; } else { echo 'NO'; }" > ~/www/mysql_loc.php
  - echo "<?php if (mysqli_connect('127.0.0.1', 'root', '')) { echo 'YES'; } else { echo 'NO'; }" > ~/www/mysql_127.php
  - echo "<?php if (mysqli_connect('mysql', 'root', '')) { echo 'YES'; } else { echo 'NO'; }" > ~/www/mysql_rem.php



###
### Test
###
script:

  ##
  ## Test plain docker
  ##
  - docker run -d -p 127.0.0.1:80:80 --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME}
  - docker ps
  - sleep 5

  - curl localhost
  - curl localhost | grep 'It works'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}"



  ##
  ## Test docker with external mounted directory
  ##
  - docker run -d -p 127.0.0.1:80:80 -v ~/www:/var/www/html --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME}
  - docker ps
  - sleep 5

  - curl localhost
  - curl localhost | grep 'Static Html'

  - curl http://localhost/index.php
  - curl http://localhost/index.php | grep '<?php'

  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}"


  ##
  ## Test docker with external mounted directory and PHP-FPM support
  ##
  - docker run -d
      -p 9000:9000
      -v ~/www:/var/www/html
      --name php cytopia/php-fpm-5.6
  - docker run
      -d -p 127.0.0.1:80:80
      -v ~/www:/var/www/html
      -e PHP_FPM_ENABLE=1
      -e PHP_FPM_SERVER_ADDR=php
      -e PHP_FPM_SERVER_PORT=9000
      --link php:php
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME}
  - docker ps
  - sleep 5

  - curl localhost
  - curl localhost | grep 'Static Html'

  - curl http://localhost/index.php
  - curl http://localhost/index.php | grep -q '<?php' && false || true

  - docker stop "$( docker ps | grep  "php" | awk '{print $1}' )"
  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "php"
  - docker rm "${MY_DOCKER_NAME}"


  ##
  ## Test docker with external mounted directory and PHP-FPM support and MySQL support
  ##
  - docker network create -d bridge my_bridge && sleep 2

  # MySQL
  - docker run -d
      -p 3306:3306
      -v ~/tmp/host-mysql-sock:/tmp/docker-mysql-sock
      -e MYSQL_SOCKET_DIR=/tmp/docker-mysql-sock
      -e MYSQL_ROOT_PASSWORD=
      --network=my_bridge
      --name mysql cytopia/mysql-5.5 && sleep 10

  # PHP
  - docker run -d
      -p 9000:9000
      -v ~/www:/var/www/html
      -v ~/tmp/host-mysql-sock:/tmp/docker-mysql-sock
      -e FORWARD_MYSQL_PORT_TO_LOCALHOST=1
      -e MYSQL_REMOTE_ADDR=mysql
      -e MYSQL_REMOTE_PORT=3306
      -e MYSQL_LOCAL_PORT=3306
      -e MOUNT_MYSQL_SOCKET_TO_LOCALDISK=1
      -e MYSQL_SOCKET_PATH=/tmp/docker-mysql-sock/mysqld.sock
      --network=my_bridge
      --link mysql
      --name php cytopia/php-fpm-5.6 && sleep 10

  # HTTP
  - docker run
      -d -p 127.0.0.1:80:80
      -v ~/www:/var/www/html
      -e PHP_FPM_ENABLE=1
      -e PHP_FPM_SERVER_ADDR=php
      -e PHP_FPM_SERVER_PORT=9000
      --network=my_bridge
      --link php
      --link mysql
      --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME} && sleep 10

  - docker ps
  - docker network ls
  - docker network inspect my_bridge


  # Test pinging
  - docker exec -ti php ping -c 2 mysql
  - docker exec -ti ${MY_DOCKER_NAME} ping -c 2 mysql

  - docker exec -ti php ping -c 2 ${MY_DOCKER_NAME}
  - docker exec -ti mysql ping -c 2 ${MY_DOCKER_NAME}

  - docker exec -ti ${MY_DOCKER_NAME} ping -c 2 php
  - docker exec -ti ${MY_DOCKER_NAME} ping -c 2 mysql


  # Wait for dockers to initialize properly
  - sleep 30

  - curl localhost
  - curl localhost | grep 'Static Html'

  - curl http://localhost/index.php
  - curl http://localhost/index.php | grep -q '<?php' && false || true

  - curl http://localhost/mysql_loc.php
  - curl http://localhost/mysql_127.php
  - curl http://localhost/mysql_rem.php

  - curl http://localhost/mysql_loc.php | grep 'YES'
  - curl http://localhost/mysql_127.php | grep 'YES'
  - curl http://localhost/mysql_rem.php | grep 'YES'

  - docker stop "$( docker ps | grep  "mysql" | awk '{print $1}' )"
  - docker stop "$( docker ps | grep  "php" | awk '{print $1}' )"
  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "mysql"
  - docker rm "php"
  - docker rm "${MY_DOCKER_NAME}"
