env:
  global:
    - MY_DOCKER_NAME="apache-2.2"


language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t cytopia/${MY_DOCKER_NAME} .

#before_script:
#  - pip install -r requirements.txt
#  - pip install mock
#  - pip install requests
#  - pip install feedparser

script:

  # Test plain
  - docker run -d -p 127.0.0.1:80:80 --name ${MY_DOCKER_NAME} cytopia/${MY_DOCKER_NAME}
  - docker ps | grep -q "${MY_DOCKER_NAME}"

  - sleep 5
  - curl localhost
  - curl localhost | grep 'It works'
  - docker stop "$( docker ps | grep  "${MY_DOCKER_NAME}" | awk '{print $1}' )"
  - docker rm "${MY_DOCKER_NAME}"


  #- python tests.py
